from enum import Enum


class LoopState(str, Enum):
    DISCOVERY = "DISCOVERY"
    PLANNING = "PLANNING"
    SCAFFOLDING = "SCAFFOLDING"
    INITIALIZING = "INITIALIZING"
    IMPLEMENTING = "IMPLEMENTING"
    SELF_CHECK = "SELF_CHECK"
    VERIFYING = "VERIFYING"
    BUG_HUNT = "BUG_HUNT"
    REWORK = "REWORK"
    READY = "READY"
    FAILED = "FAILED"
